// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: HoverBotBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node3 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((HoverBotAgent)pAgent).HasTarget();
			bool opr = false;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node1 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node1()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoPatrol();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node6 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node6()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoChase();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node8 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node8()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			float opl = ((HoverBotAgent)pAgent).GetTargetDist();
			float opr = 10f;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node10 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node10()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((HoverBotAgent)pAgent).TargetInView();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node4 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node4()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoAttack();
			return result;
		}
	}

	public static class bt_HoverBotBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("HoverBotBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("HoverBotAgent");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("HoverBotAgent");
#endif
				bt.AddChild(node0);
				{
					Sequence node2 = new Sequence();
					node2.SetClassNameString("Sequence");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node2);
					{
						Condition_bt_HoverBotBT_node3 node3 = new Condition_bt_HoverBotBT_node3();
						node3.SetClassNameString("Condition");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("HoverBotAgent");
#endif
						node2.AddChild(node3);
						node2.SetHasEvents(node2.HasEvents() | node3.HasEvents());
					}
					{
						Action_bt_HoverBotBT_node1 node1 = new Action_bt_HoverBotBT_node1();
						node1.SetClassNameString("Action");
						node1.SetId(1);
#if !BEHAVIAC_RELEASE
						node1.SetAgentType("HoverBotAgent");
#endif
						node2.AddChild(node1);
						node2.SetHasEvents(node2.HasEvents() | node1.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Selector node5 = new Selector();
					node5.SetClassNameString("Selector");
					node5.SetId(5);
#if !BEHAVIAC_RELEASE
					node5.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node5);
					{
						Sequence node7 = new Sequence();
						node7.SetClassNameString("Sequence");
						node7.SetId(7);
#if !BEHAVIAC_RELEASE
						node7.SetAgentType("HoverBotAgent");
#endif
						node5.AddChild(node7);
						{
							Action_bt_HoverBotBT_node6 node6 = new Action_bt_HoverBotBT_node6();
							node6.SetClassNameString("Action");
							node6.SetId(6);
#if !BEHAVIAC_RELEASE
							node6.SetAgentType("HoverBotAgent");
#endif
							node7.AddChild(node6);
							node7.SetHasEvents(node7.HasEvents() | node6.HasEvents());
						}
						{
							Condition_bt_HoverBotBT_node8 node8 = new Condition_bt_HoverBotBT_node8();
							node8.SetClassNameString("Condition");
							node8.SetId(8);
#if !BEHAVIAC_RELEASE
							node8.SetAgentType("HoverBotAgent");
#endif
							node7.AddChild(node8);
							node7.SetHasEvents(node7.HasEvents() | node8.HasEvents());
						}
						node5.SetHasEvents(node5.HasEvents() | node7.HasEvents());
					}
					{
						Sequence node9 = new Sequence();
						node9.SetClassNameString("Sequence");
						node9.SetId(9);
#if !BEHAVIAC_RELEASE
						node9.SetAgentType("HoverBotAgent");
#endif
						node5.AddChild(node9);
						{
							Condition_bt_HoverBotBT_node10 node10 = new Condition_bt_HoverBotBT_node10();
							node10.SetClassNameString("Condition");
							node10.SetId(10);
#if !BEHAVIAC_RELEASE
							node10.SetAgentType("HoverBotAgent");
#endif
							node9.AddChild(node10);
							node9.SetHasEvents(node9.HasEvents() | node10.HasEvents());
						}
						{
							Action_bt_HoverBotBT_node4 node4 = new Action_bt_HoverBotBT_node4();
							node4.SetClassNameString("Action");
							node4.SetId(4);
#if !BEHAVIAC_RELEASE
							node4.SetAgentType("HoverBotAgent");
#endif
							node9.AddChild(node4);
							node9.SetHasEvents(node9.HasEvents() | node4.HasEvents());
						}
						node5.SetHasEvents(node5.HasEvents() | node9.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node5.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
